---
title: "Untitled"
output: html_document
date: "2023-10-13"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
chrom_wid <- 0.05
thinw <- 0.28
blstw <- 0.48

load("./EH23ideo.RData")
#
pEH23

load("./EH23ideo_ahplot.RData")
ahplot
```




```{r}
tbl1 <- read.table("EH23a_EH23b_ortholog_blast_fractionation.txt", sep = " ")
tbl1[1:3, ]

all(sub("EH23a\\.", "", tbl1[, 1]) == sub("EH23b\\.", "", tbl1[, 2]))


tbl2 <- read.table("quant.tsv", header = TRUE, sep = "\t")
tbl2[1:3, ]
```


```{r}
tbl2[1:3, ]
table(tbl2$Sample)
nrow(tbl2)

my_chroms <- sub("\\.v1.+", "", tbl2$Name)
table(my_chroms)

tbl2$CHROM <- sub("EH23.\\.", "", my_chroms)
tbl2$hap <- sub("\\.chr.", "", my_chroms)

hist(log2(tbl2$TPM))
hist(log2(tbl2$TPM[ tbl2$hap == "EH23a"]))
hist(tbl2$TPM[ tbl2$hap == "EH23a"])
#hist(log2(tbl2$NumReads))

hist(log2(tbl2$NumReads[ tbl2$hap == "EH23a"]), breaks = seq(-10, 25, by = 1))
hist(log2(tbl2$NumReads[ tbl2$hap == "EH23b"]), breaks = seq(-10, 25, by = 1))


```


```{r}
library(ggplot2)

tbl2[1:3, ]

p <- ggplot(tbl2, aes( x = log2(TPM) ))
p <- p + geom_histogram()
p <- p + theme_bw()
p <- p + scale_y_continuous(name = "Count (K)", breaks = seq(0, 60e3, by = 20e3), labels = seq(0, 60, by = 20))
p
#library(scales)
#
#p + scale_y_continuous(labels = scientific)
```



## ggpubr


```{r}
library(ggpubr)

ggarrange(
  plotlist = list(pEH23, ahplot),
  labels = c("A", "B"),
  label.x = 0,
  label.y = c(1, 1.1),
  ncol = 1, nrow = 2, 
  widths = 1, heights = c(2, 1)
)

```


```{r}
library(ggpubr)

p1 <- ggarrange(
  plotlist = list(pEH23, ahplot),
  labels = c("A", "B"),
  label.x = 0,
  label.y = c(1, 1.1),
  ncol = 1, nrow = 2, 
  widths = 1, heights = c(2, 1)
)

p2 <- ggarrange(
  plotlist = list(p, p, p),
  labels = c("C", "D", "E"),
  label.x = 0,
  label.y = c(1, 1.1),
  ncol = 1, nrow = 3, 
  widths = 1, heights = c(2, 1, 1)
)

p3 <- ggarrange(
  plotlist = list(p1, p2),
#  labels = c("C", "D", "E"),
#  label.x = 0,
#  label.y = c(1, 1.1),
  ncol = 2, nrow = 1, 
  widths = c(2, 1), heights = 1)

p3

ggsave( filename = "EH23_ideo_exp.tiff", device = "tiff", 
        width = 6.5, 
        height = 6.5,
        #height = 9,
        units = "in", dpi = 300, 
        compression = "lzw")

```



