---
title: "Cannabis query sequences"
output: 
  html_document:
    code_folding: hide
    toc: true
date: "2023-02-12"
editor_options: 
  chunk_output_type: console
bibliography: ../bibliography.bib
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## Maize analogs???


## CBCAS, CBDAS, THCAS

LY658671.1 == CBCAS1
(https://www.ncbi.nlm.nih.gov/nuccore/LY658671.1)

```
>LY658671.1 KR 1020190025485-A/5: CANNABICHROMENIC ACID SYNTHASE FROM CANNABIS SATIVA
ATGAATTGCTCAACATTCTCCTTTTGGTTTGTTTGCAAAATAATATTTTTCTTTCTCTCATTCAATATCC
...
CCCACCTCTTCCACCGCGTCATCAT
```

AB292682_CBDAS1
[@taura2007cannabidiolic]
https://www.ncbi.nlm.nih.gov/nuccore/AB292682.1


```
AB292682.1 Cannabis sativa CBDAS mRNA for cannabidiolic acid synthase, complete cds
ATGAAGTGCTCAACATTCTCCTTTTGGTTTGTTTGCAAGATAATATTTTTCTTTTTCTCATTCAATATCC
...
ACCTCTTCCACGGCATCGTCATTAA
```

AB292683_CBDAS2
[@taura2007cannabidiolic]
https://www.ncbi.nlm.nih.gov/nuccore/AB292683.1

```
>AB292683.1 Cannabis sativa CBDAS2 mRNA for cannabidiolic acid synthase homolog, complete cds
ATGAAGTGCTCAACATTCTGTTTTTGGTATGTTTGCAAGATAATATTTTTCTTTCTCTCATTCAATATCC
...
CCCACCTCTTCCCCTGCGTCATCATTAA
```

AB292684_CBDAS3
[@taura2007cannabidiolic]
https://www.ncbi.nlm.nih.gov/nuccore/AB292684.1

```
>AB292684.1 Cannabis sativa CBDAS3 mRNA for cannabidiolic acid synthase homolog, complete cds
ATGAAGTGCTCAACATTCTGTTTTTGGTATGTTTGCAAGATAATATTTTTCTTTCTCTCATTCAATATCC
...
CCCACCTCTTCCCCTGCGTCATCATTAA
```

AB212829_THCAS1
[@kojoma2006dna]
https://www.ncbi.nlm.nih.gov/nuccore/AB212829

```
>AB212829.1 Cannabis sativa gene for tetrahydrocannabinolic acid synthase, partial cds, strain:001
ATGAATTGCTCAGCATTTTCCTTTTGGTTTGTTTGCAAAATAATATTTTTCTTTCTCTCATTCCATATCC
...
CCCACCTCTTCCACCGCATCATCAT
```

AB212830_THCAS2
[@kojoma2006dna]
https://www.ncbi.nlm.nih.gov/nuccore/AB212830


```
>AB212830.1 Cannabis sativa gene for tetrahydrocannabinolic acid synthase, partial cds, strain:005
ATGAATTGCTCAGCATTTTCCTTTTGGTTTGTTTGCAAAATAATATTTTTCTTTCTCTCATTCAATATCC
...
CCCACCTCTTCCACCGCATCATCAT
```

## Sub-telomeric motif and centromeric motif


https://www.ncbi.nlm.nih.gov/nuccore/ON055367.1?report=genbank

```
>ON055367.1 Cannabis sativa clone 26 satellite CS-237 sequence
CATCCCTAATCACCCAACGTGAACGCCCGCCGAAATCCCATCGAAAGGTGGTGACGCTGGATGATTTCAA
ATGAGTGTCGGCAATACATCACTCCGACAATGAAGTCGGTTCAGACAGCTTTCAAACATCCTCAATCAAA
CAACGTAACCACCAAGTGGATGGTTGTGACGCCGCATGATTTTAGACGAGTGTCCCCCATCCTTCTGACA
ATGAAGTCGGTCAAGATGGCTTTCAAA
```

https://www.ncbi.nlm.nih.gov/nuccore/ON055366.1

```
>ON055366.1 Cannabis sativa clone 25 satellite CS-237 sequence
AATCACCCAACGTGAACGCCCGCCGAAATCCCATCGAAAGGTGGTGACGCTGGATGATTTCAAATGAGTG
TCGGCAATACATCACTCCGACAATGAAGTCGGTTCAGACAGCTTTCAAACATCCTCAATCAAACAACGTA
ACCACCAAGTGGATGGTTGTGACGCCGCATGATTTTAGACGAGTGTCCCCCATCCTTCTGACAATGAAGT
CGGTCAAGATGGCTTTCAAACATCCTC
```

https://www.ncbi.nlm.nih.gov/nuccore/JX402748.2

```
>JX402748.2 Cannabis sativa subtelomeric tandem repeat sequence
GGTACCACTATGAGAAATGTGAGATTTTTACTATTTTTATTAAAATGATTGTTAGTGCATGGAAACTATT
TTTTCTCTCAATGCATCCAATAGAAAAGTGATGCACAACAGTCTTGGTTTTTTCTCCGTGAAATTTAACG
ATTTTTAGAGATGTGTAGGGAGAGATTTTAATAGAACACTAACGTGTGCAAGAGTAAGGAAAGAACTTAT
TAAAATTTACCCTAAAAAGGAGAATATATTAAATTTTTGAATTAGGGGGCCATTTTAATCAAATTTAACG
CGAAACCAATCTTCATATTCATGTCTTAGTAGCACGAATTCAATGTGACTAGTGCCAAAAAATAATCTGA
GATGAGTCCGGGCCACATTTCACAAAGG
```


## CENP

CENP AND Cannabis sativa[Organism] 


CENP-B homolog protein 2-like

```
>NC_044371.1:c59909808-59908167 Cannabis sativa chromosome 1, cs10, whole genome shotgun sequence
ATGCCTCCCATAGCCAAAATACGTGTTCATCTCACTGAAAGTATTCGTGTTAAACTATGCCGAATAAAGA
...
TTTGGGTTTTTTTAGTATGTACCTCTATTTAG
```

uncharacterized LOC115700075 

```
>NC_044370.1:c100762796-100755478 Cannabis sativa chromosome X, cs10, whole genome shotgun sequence
TCGGGTAAAGCCAACCAACCACCCAACCCATTTCTTCTTCTTCTTCTTCGTCTTCTTCAATATTCTCCGC
...
TTTACATTTTTACATAAAGAATGAAATTATTGTGTACTA
```

kinesin-like protein KIN-7E

```
>NC_044377.1:73029451-73035487 Cannabis sativa chromosome 6, cs10, whole genome shotgun sequence
CTAGAGAAACTTCAACGACGTTGACGCTCCAACCAGATTTGCAGGACCCTTTTGGTCCAATCCCACGTAT
...
AGCTGTGTTATTATATA
```

protein MHF2 homolog 

```
>NC_044372.1:10733713-10736146 Cannabis sativa chromosome 3, cs10, whole genome shotgun sequence
CATGAAATTTACAACTCTAATTTAAAATTGAAACAAAAAGGGAGAAACTGAAGATGAAGAAGACTGAATA
...
AATATTTAGGAAATTGGAATAACTGTTTTTATTTTTCAAAGTGATCTTGTAATG
```

kinesin-like protein KIN-7G

```
>NC_044373.1:85658219-85664691 Cannabis sativa chromosome 4, cs10, whole genome shotgun sequence
AGGGAAGCAATGAAAGGTCGAAAACCAACTAACAATTTAGCAAAAGAAGCAGACGCCATAACCACTTTAA
...
CGAAATTTATTTATTTTGTTTTATTTTTTGGGA
```

kinesin-like protein KIN-7D, mitochondrial 

```
>NC_044377.1:c74279067-74269267 Cannabis sativa chromosome 6, cs10, whole genome shotgun sequence
TCACTACCACTCACGCCAGTTCTTTCTCTTTCTCTCTCTTCATTTTCTTTCTTCTCTGCAACTCAAACTC
...
GATTGGTCTTGTATAGAAACAAACAAATATATTCGTAACAAAATTTATATATATGTTTTTGTTTTCTTTT
A
```

E3 ubiquitin-protein ligase BOI 

```
>NC_044373.1:c3920096-3916970 Cannabis sativa chromosome 4, cs10, whole genome shotgun sequence
ATATTTCATATACACATATACACATATACACACACACTAATAATAATTTGGCCACTTCTTCATACCCGTC
...
ACATTAGTTTTATTTGCCTTAATGTAATTAATTAGTTTATGTGATCA
```

kinesin-like protein NACK1

```
>NC_044372.1:c74031678-74026573 Cannabis sativa chromosome 3, cs10, whole genome shotgun sequence
CACATTGGTTTTTCTTGTCTCTGTTAAAATATTCAACCATAAAGATGACAGTCAGGACTCCTGGAACACC
...
ATTTTATTCATTTTTTTTTTGTAATTAATTTCGTTATTTATTTATCTATTCTATGTAAATGGTGAA
```

kinesin-like protein KIN-7C, mitochondrial 

```
>NC_044370.1:c25070310-25061118 Cannabis sativa chromosome X, cs10, whole genome shotgun sequence
TTGTTTTTGGAGGGAGAGATAGCTGAGCTGAGAGAGAAGAAGACTGTTTCTTCTTCTTCCCAAAACCCTT
...
CCTATCAAAAAGTATTGACTCTA
```

kinesin-like protein KIN-7B

```
>NC_044371.1:51115261-51120610 Cannabis sativa chromosome 1, cs10, whole genome shotgun sequence
CACGAGCGTGGCATTCAATTGCAGCGCGTTACGAACGGAAAAAGTAGCCGTTAGTTCTACAGATTTGAGT
...
CTCTTTTTCCTCCTCATATGTTGCCGTGTA
```

protein MHF1 homolog

```
>NC_044371.1:74486649-74488506 Cannabis sativa chromosome 1, cs10, whole genome shotgun sequence
CTTGCCCTTTATCTTTTGTTCACTGTTCACTATACCCCCTTTCATTTTGGCGCCAGAAAAAGTAAAGGGC
...
GATTAGCAATCACACAAATAGAAAAATCTTTCACGACA
```

kinesin-like protein KIN-7O 

```
>NC_044379.1:c30883014-30869069 Cannabis sativa chromosome 8, cs10, whole genome shotgun sequence
CCTTTTCTCCAAAGAGTAGGATCTCGAGAAGATTAGCCGACTGAGATTCATTTGAGGTCCCCAGATTGAT
...
GTGTTGAATTATATTATATTGTAGAATACAAAGTATGGTATTGTTTATAGCTGCTGTTAATAAATGTATT
TATCTTTGTACAAGAA
```

kinesin-like protein KIN-7K, chloroplastic 

```
>NC_044379.1:28467758-28483463 Cannabis sativa chromosome 8, cs10, whole genome shotgun sequence
GTACATATTCTCTTTTTCTCTCTCCAAAAAGAAAAAGAAAAAGAAAGCTAAAAGAGAAAGGTTGGGATTG
...
AGAGAGAGAGAGAGTGAGTGAGTGAGAGTGTACAAATTTGTGCTGTGGATTGCAGGGTTTTCTTGTGTAT
ATGAAAAGAGCTTTTTTGTTTGTTTT

```

kinesin-like protein KIN-7N

```
>NC_044370.1:c87556506-87549575 Cannabis sativa chromosome X, cs10, whole genome shotgun sequence
AAAAAAAGGTTCACGTGAAGTGAAGGGCAATTAAGTAAAGTGGGGAGAATTCAAATTTACAAATGGCGCA
...
TAAATTAGAAAACAAGTAAAATGATTCATTTATTGTAGTAATAATATGAAATGAGTGTGAACGAACCGAA
TA
```

kinesin-like protein NACK1

```
>NC_044372.1:73932213-73938251 Cannabis sativa chromosome 3, cs10, whole genome shotgun sequence
AAAAAAAAAAAAAAAAGAAAAACCATAACGCACGGTCCTCACACCCAGTTAGTTTCCACTACTATTACTG
...
ATAGTGTATGTGATTGATAACTGGGGATGCTTTTGTAATTGATAAACCAATTCAATTAGTTGAATTCCAA
CTGCCACCTTGAATAACTG
```

protein MHF1 homolog

```
>NC_044371.1:c74285628-74284242 Cannabis sativa chromosome 1, cs10, whole genome shotgun sequence
CTTTCATTTTGGCGCCAGAAAAAGTAAAGGGACCCCAAGGCTCGAGTAAACCATGGTGGACACGGAGGAG
...
TGAGTTGAAAGCCAAAGAACCTCAATCTGAAAGGAAGCGAAAGAAAGGACCGAGGAAGGAAGACAAATTG
AGAGCAAGTACAAGTGCTGTGCATATTGAAGACTAGTTACTATAATAAAAAAAACAA
```


## Ribosomal RNA

novel hemp tandem repeat CS-237 that is linked with IGS 18S-26S rDNA 


## Ribosomal RNA

5S ribosomal RNA

```
>NC_044375.1:87745002-87745120 Cannabis sativa chromosome 2, cs10, whole genome shotgun sequence
GGGCGCGATCTTACCTGCACTAATGCACCGGATCCCATAAGAACTCCGCAATTAAGCTTGCTTGGGCGAG
AATAGTACTAGGATGGGTGACCTCCTGGGAAGTCCTCGTATTGCACCCA
```

5S ribosomal RNA

```
>NC_044375.1:c53695768-53695650 Cannabis sativa chromosome 2, cs10, whole genome shotgun sequence
GGGTGCGATCATACCAGCACTAATGCACCGGATCCCATCAGAACTCCGCAGTTAAGCGTGCTTGGGCGAG
AGTAGTACTACGATGGGTGACCTCCTGGGAAGTCCTCGTGTTGCACCCC
```

5S ribosomal RNA

```
>NC_044374.1:c44833076-44832958 Cannabis sativa chromosome 5, cs10, whole genome shotgun sequence
GGGTGCGATCATACCAGCACTAATGCACCGGATCCCATCAGAACTCCGCAGTTAAGCGTGCTTGGGCGAG
AGTAGTACTAGGATGGGTGACCTCCTGGGAAGTCCTCGTGTTGCACCCC
```

5.8S ribosomal RNA

```
>NW_022060381.1:1971-2125 Cannabis sativa unplaced genomic scaffold, cs10 ctgX162, whole genome shotgun sequence
AGCTCTCGGCAGCGGATATCTCGGCTCTCGCATCGATGAAGAACGTGGCGAAATCACGATACTTGGTGTG
AATTGCAGAATCCGTGAACCATCGAGTCTTTGAGCACGCAAGTTAAGCCACTAGGCACAAGTAGAGGCAC
GTCTGCCTGGCGTCT
```

5S ribosomal RNA

```
>NW_022060319.1:43075-43193 Cannabis sativa unplaced genomic scaffold, cs10 ctgX100, whole genome shotgun sequence
GGGTGCGATCATACCAGCACTAATGCACCGGATCCCATCAGAACTCCGCAGTTAAGCGTGCTTGGGCGAG
AGTAGTACTAGGATGGGTGACCTCCTGGGAAGTCCTCGTGTTGCACCCC
```

5.8S ribosomal RNA

```
>NC_044379.1:3564222-3564376 Cannabis sativa chromosome 8, cs10, whole genome shotgun sequence
GACTCTCGGCAACGGATATCTCGGCTCTCGCGATCGATGAAGAACGAGCGAAATGCGATACTTGGTGTGA
ATTGCAGAATCCCGTGAACCATCGAAGTCTTTGAACGCAAGTTGCGCCCGGCCACTAGGCCGAGGGCACG
TCTGCCTGGGCGTCA
```

5.8S ribosomal RNA

```
>NC_044379.1:3555042-3555197 Cannabis sativa chromosome 8, cs10, whole genome shotgun sequence
GACTCTCGGCAACGGATATCTCGGCTCTCGCATCGATGAAGAACGTAGCGAAATGCGATACTTGGTGTGA
ATTGCAGAATCCCGTGAACCATCGAGTCTTTGAACGCAAGTTGCGCCCGAAGCCACTAGGCCGAGGGCAC
GTCTGCCTGGGCGTCA
```

28S ribosomal RNA

```
>NC_044379.1:3564598-3567870 Cannabis sativa chromosome 8, cs10, whole genome shotgun sequence
CGACCCGTGTCAGCGGGATCACCCGCTGAATTTAAGCATATCAATAAGCGGAGGAAAAGAAACTTACAAG
...
ACAATTCCTACCGAACGGCGGTAGAATCCTTTGCAGACGACTTAAGCACGCGACGGTATTGTAAGTGGCG
AGTGGCCTTGCCGCCACGATCCACCGAGATTCAGCCCCGTGTCGCCGATTCGC
```

28S ribosomal RNA

```
>NC_044379.1:3555419-3558812 Cannabis sativa chromosome 8, cs10, whole genome shotgun sequence
CGACCCCAGGTCAGGCGGGATCACCCGCTGAATTTAAGCATATCAATAAGCGGAGGAAAAGAAACTTACA
...
AATCCTTTGCAGACGACTTAAGTACGCGACGGGGTATTGTAAGTGGCAGAGTGGCCTTGCTGCCACGATC
CACTGAGATTCAGCCCTGTGTCGCTCAGATTCGT
```

18S ribosomal RNA

```
>NC_044379.1:3562204-3563993 Cannabis sativa chromosome 8, cs10, whole genome shotgun sequence
TACCTGGTTGATCCTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATGCATGTGTAAGTATGAAC
...
TGGGCGGTTCGCTGCCCGCGACGTAGCGAGAAGTCCACTGAACCTTATCATTTAGAGGAAGGAGAAGTCG
TAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTG
```

18S ribosomal RNA

```
>NC_044379.1:3553004-3554811 Cannabis sativa chromosome 8, cs10, whole genome shotgun sequence
TACCTGGTTGATCCTGCCAGTAGTCATATGCTTGTCTCAAAGATTAAGCCATGCATGTGTAAGTATGAAC
...
GTTCGGATCGAGGCGACGTGGGCGGTTCGCTGCCCGCGACGTAGCGAGAAGTCCACTGAACCTTATCATT
TAGAGGAAGGAGAAGTCGTAACAAGGTTTCCGTAGGTGAACCTGCGGAAGGATCATTG
```

5S ribosomal RNA

```
>NC_044378.1:c34041532-34041414 Cannabis sativa chromosome 7, cs10, whole genome shotgun sequence
AAAAGCGATCATACCAGCACTAATGCACCGGATCCCATCAGAACTCCGCAGTTAAGCGTGCTTGGGCGAG
AGTAGTACTAGGATGGGTGACCTCCTGAAGAGTCCTCGTTTTGCACCCC
```

5S ribosomal RNA

```
>NC_044378.1:c34042045-34041926 Cannabis sativa chromosome 7, cs10, whole genome shotgun sequence
GCAAGCGATCATACCAAAGACTAATGCACCGGATCCCATCAGAACTCCGCAGTTAAGCGTGCTTGGGCGA
GAGTAGTACTAGGATGGGTGACCTCCTGGGAAGTCCTCGTGTTGCACCCC
```

5S ribosomal RNA

```
>NC_044378.1:c34042304-34042186 Cannabis sativa chromosome 7, cs10, whole genome shotgun sequence
GGGTGCGATCATACCAGCACTAATGCACCGGATCCCATCAGAACTCCGCAGTTAAGCGTGCTTGGGCGAG
AGTAGTACTAGGATGGGTGACCTCCTGGGAAGTCCTCGTGTTGCACCCC
```

5S ribosomal RNA

```
>NC_029855.1:381430-381544 Cannabis sativa mitochondrion, complete genome
CCGGGCTTGGACCATGTCTCCCGAACAATCTCAGTACATATGGCGCAAGACGATTCCACATATCGAGGTC
GGAATGGGATCGGGTGTTTTCACGTCTCACCGTAGTGCCCGGTTT
```

23S ribosomal RNA

```
>NC_027223.1:c133620-130812 Cannabis sativa cultivar Yoruba Nigeria chloroplast, complete genome
TCAAACGAGGAAAGGCTTACGGTGGATACCTAGGCACCCAGAGACGAGGAAGGGCGTAATAAGCGACGAA
...
CGCTGGGTAGCCAAGTGCGGAGCGGATAACTGCTGAAAGCATCTAAGTAGTAAGCCCACCCCAAGATGAG
TGCTCTCCT
```

4.5S ribosomal RNA

```
>NC_027223.1:c130713-130611 Cannabis sativa cultivar Yoruba Nigeria chloroplast, complete genome
GAAGGTCACGGCGAGACGAGCCGTTTATCATTACGATAGGTGTCAAGTGGAAGTGCAGTGATGTATGCAG
CTGAGGCATCCTAACAGACCGGTAGACTTGAAC
```

5S ribosomal RNA

```
>NC_027223.1:107536-107656 Cannabis sativa cultivar Yoruba Nigeria chloroplast, complete genome
TATTCTGGTGTCCTAGGCGTAGAGGAACCACACCAATCCATCCCGAACTTGGTGGTTAAACTCTACTGCG
GTGACGATACTGTAGGGGAGGTCCTGCGGAAAAATAGCTCGACGCCAGGAT
```


4.5S ribosomal RNA

```
>NC_027223.1:107169-107271 Cannabis sativa cultivar Yoruba Nigeria chloroplast, complete genome
GAAGGTCACGGCGAGACGAGCCGTTTATCATTACGATAGGTGTCAAGTGGAAGTGCAGTGATGTATGCAG
CTGAGGCATCCTAACAGACCGGTAGACTTGAAC
```


16S ribosomal RNA

```
>NC_027223.1:100354-101844 Cannabis sativa cultivar Yoruba Nigeria chloroplast, complete genome
TCTCATGGAGAGTTCGATCCTGGCTCAGGATGAACGCTGGCGGCATGCTTAACACATGCAAGTCGGACGG
...
AAGGAGGGGGATGCCGAAGGCAGGGCTAGTGACTGGAGTGAAGTCGTAACAAGGTAGCCGTACTGGAAGG
TGCGGCTGGATCACCTCCTTT
```

5S ribosomal RNA

```
>NC_027223.1:c130346-130226 Cannabis sativa cultivar Yoruba Nigeria chloroplast, complete genome
TATTCTGGTGTCCTAGGCGTAGAGGAACCACACCAATCCATCCCGAACTTGGTGGTTAAACTCTACTGCG
GTGACGATACTGTAGGGGAGGTCCTGCGGAAAAATAGCTCGACGCCAGGAT
```

23S ribosomal RNA

```
>NC_027223.1:104261-107069 Cannabis sativa cultivar Yoruba Nigeria chloroplast, complete genome
TTCAAACGAGGAAAGGCTTACGGTGGATACCTAGGCACCCAGAGACGAGGAAGGGCGTAATAAGCGACGA
...
ACGCTGGGTAGCCAAGTGCGGAGCGGATAACTGCTGAAAGCATCTAAGTAGTAAGCCCACCCCAAGATGA
GTGCTCTCC
```

16S ribosomal RNA

```
>NC_027223.1:c137528-136038 Cannabis sativa cultivar Yoruba Nigeria chloroplast, complete genome
TCTCATGGAGAGTTCGATCCTGGCTCAGGATGAACGCTGGCGGCATGCTTAACACATGCAAGTCGGACGG
...
AAGGAGGGGGATGCCGAAGGCAGGGCTAGTGACTGGAGTGAAGTCGTAACAAGGTAGCCGTACTGGAAGG
TGCGGCTGGATCACCTCCTTT
```

23S ribosomal RNA

```
>NC_026562.1:c133640-130832 Cannabis sativa cultivar Carmagnola chloroplast, complete genome
TCAAACGAGGAAAGGCTTACGGTGGATACCTAGGCACCCAGAGACGAGGAAGGGCGTAATAAGCGACGAA
...
CGCTGGGTAGCCAAGTGCGGAGCGGATAACTGCTGAAAGCATCTAAGTAGTAAGCCCACCCCAAGATGAG
TGCTCTCCT
```


4.5S ribosomal RNA

```
>NC_026562.1:c130733-130631 Cannabis sativa cultivar Carmagnola chloroplast, complete genome
GAAGGTCACGGCGAGACGAGCCGTTTATCATTACGATAGGTGTCAAGTGGAAGTGCAGTGATGTATGCAG
CTGAGGCATCCTAACAGACCGGTAGACTTGAAC
```


5S ribosomal RNA

```
>NC_026562.1:107550-107670 Cannabis sativa cultivar Carmagnola chloroplast, complete genome
TATTCTGGTGTCCTAGGCGTAGAGGAACCACACCAATCCATCCCGAACTTGGTGGTTAAACTCTACTGCG
GTGACGATACTGTAGGGGAGGTCCTGCGGAAAAATAGCTCGACGCCAGGAT
```


4.5S ribosomal RNA

```
>NC_026562.1:107183-107285 Cannabis sativa cultivar Carmagnola chloroplast, complete genome
GAAGGTCACGGCGAGACGAGCCGTTTATCATTACGATAGGTGTCAAGTGGAAGTGCAGTGATGTATGCAG
CTGAGGCATCCTAACAGACCGGTAGACTTGAAC
```


16S ribosomal RNA

```
>NC_026562.1:c137548-136058 Cannabis sativa cultivar Carmagnola chloroplast, complete genome
TCTCATGGAGAGTTCGATCCTGGCTCAGGATGAACGCTGGCGGCATGCTTAACACATGCAAGTCGGACGG
...
AAGGAGGGGGATGCCGAAGGCAGGGCTAGTGACTGGAGTGAAGTCGTAACAAGGTAGCCGTACTGGAAGG
TGCGGCTGGATCACCTCCTTT
```

5S ribosomal RNA

```
>NC_026562.1:c130366-130246 Cannabis sativa cultivar Carmagnola chloroplast, complete genome
TATTCTGGTGTCCTAGGCGTAGAGGAACCACACCAATCCATCCCGAACTTGGTGGTTAAACTCTACTGCG
GTGACGATACTGTAGGGGAGGTCCTGCGGAAAAATAGCTCGACGCCAGGAT
```



23S ribosomal RNA

```
>NC_026562.1:104275-107083 Cannabis sativa cultivar Carmagnola chloroplast, complete genome
TTCAAACGAGGAAAGGCTTACGGTGGATACCTAGGCACCCAGAGACGAGGAAGGGCGTAATAAGCGACGA
...
ACGCTGGGTAGCCAAGTGCGGAGCGGATAACTGCTGAAAGCATCTAAGTAGTAAGCCCACCCCAAGATGA
GTGCTCTCC
```


16S ribosomal RNA

```
>NC_026562.1:100368-101858 Cannabis sativa cultivar Carmagnola chloroplast, complete genome
TCTCATGGAGAGTTCGATCCTGGCTCAGGATGAACGCTGGCGGCATGCTTAACACATGCAAGTCGGACGG
...
AAGGAGGGGGATGCCGAAGGCAGGGCTAGTGACTGGAGTGAAGTCGTAACAAGGTAGCCGTACTGGAAGG
TGCGGCTGGATCACCTCCTTT
```





## OAS

olivetolic acid cyclase-like 

```
>NC_044376.1:c4279947-4279296 Cannabis sativa chromosome 9, cs10, whole genome shotgun sequence
CTGTATGTAGCATAATGTGATTTATATAATTATCAAAAAAAAAAAAAAAGAAGAAGAAGAAGAAAGTTGA
GAAAGAGAATGGCAGTGAAGCATTTGATTGTATTGAAGTTCAAAGATGAAATCACAGAAGCCCAAAAGGA
AGAATTTTTCAAGACGTATGTGAATCTTGTGAATATCATCCCAGCCATGAAAGATGTATACTGGTAATTT
GTGATTATTTTGTTTCATAATTCATACATTTAATTAATTATAATAATAGTATAGTCATGAATATAATTCT
AATAATGTTGTTTGCCATTGCAGGGGTAAAGATGTGACTCAAAAGAATAAGGAAGAAGGGTACACTCACA
TAGTTGAGGTAACATTTGAGAGTGTGGAGACTATTCAGGACTACATTATTCATCCTGCCCATGTTGGATT
TGGAGATGTCTATCGTTCTTTCTGGGAAAAACTTCTCATTTTTGACTACACACCACGAAAGTAGACTATA
TATATATATATATATATATATAGTCTCCCACTGCCCACTGAATGGACCAAGCTGCAGCCTTCATCTTCAT
TTTCTCGAATAATATTATATATATCTAATAAATATGTGTAACTCTTTGATAAATTTAATAATACAAGTAC
TCCTACTCTTTATTACTTGTTA
```

olivetolic acid cyclase 



```
>NC_044376.1:c4272107-4271242 Cannabis sativa chromosome 9, cs10, whole genome shotgun sequence
TTTGTGGTTATTTAATTTTAGACATAGTGTGATCCAATAATTTTAGGATGTATAATTGTTAGGCACATGG
ATTACTTGTTTTTTTATAAAGTATAACCTTACAAAGTAGATGGTAGTAATTAATGTAGAAGGTTCCAATG
ATGTATTTATATAAATTGTTAGGCATGCAAAGCCTAATTAATTAATAAATGAGGGTGGCCAATGGCCACT
ATATATATCAAGGCATCGACTGTATGTAGCATAATGTGATTTATATAATTATCAAAAAAAAAAAAAAGAA
GAAGAAGAAGAAAGTTGAGAAAGAGAATGGCAGTGAAGCATTTGATTGTATTGAAGTTCAAAGATGAAAT
CACAGAAGCCCAAAAGGAAGAATTTTTCAAGACGTATGTGAATCTTGTGAATATCATCCCAGCCATGAAA
GATGTATACTGGTAATTTGTGATTATTTTGTTTCATAATTCATACATTTAATTAATTATAATAATAGTAT
AGTCATGAATATAATTCTAATAATGTTGTTTGCCATTGCAGGGGTAAAGATGTGACTCAAAAGAATAAGG
AAGAAGGGTACACTCACATAGTTGAGGTAACATTTGAGAGTGTGGAGACTATTCAGGACTACATTATTCA
TCCTGCCCATGTTGGATTTGGAGATGTCTATCGTTCTTTCTGGGAAAAACTTCTCATTTTTGACTACACA
CCACGAAAGTAGACTATATATATATATATAGTACCGGACCAAGCTGCCTTCATCTTCATCTTCTCAAATA
ATATATCTAATATCTAATTATATAATAATAACTACTTAATAAAAGACTGTGTTTATAACATTAAATAATA
ATAATAATAAAGTCTTTTGTAGCTCA
```

## CBG

The THCAS gene sequence of TS1-3 was submitted to GenBank (accession number MT338560).

```
>MT338560.1 Cannabis sativa tetrahydrocannabinolic acid synthase (THCAS) gene, complete cds
ATGAATTGCTCAGCATTTTCCTTTTGGTTTGTTTGCAAAATAATATTTTTCTTTCTCTCATTCCATATCC
...
ATTTTAACAGGTTAGTTAAGGTGAAAACTAAAGTTGATCCCAATAATTTTTTTAGAAACGAACAAAGTAT
CCCACCTCTTCCACCGCATCATCATTAA
```


## Flowering time / autoflower



## Powdery mildew

[@10.3389/fagro.2021.720215]

```
>PNW39_LH3804_locus
CAATGCCAACATTAGAAAAGCTACCAAAATTAAGTGTCCTTATAMTTGGTTTTAATAGT
TATATAGGRGAAGAGATGGTGTGCTCAAGARGRGGTTTCCCWCRACTTGAATCTCTMRA
GTTTGATTTTCTAASTGGCTTAAAAGAGTGGAARGTGGMRGAGAATGCACTGSCTAAAC
TTGGCTATTTGRGTATTCGCGGGTGCATGAGATTGAGGAGAGTTCCAGATGGACTAAGA
AAMATTGGTACACTCAATGAGATGGTGATGGATCATATGCCTATGAAATTCAAAGAAAG
GATGGAGGAAGGAGGAGACGATTTCGATCAAGTCAAGCTCGTGCCATCACGTGTATTTA
TCAACTGTGATCAAGGTACATTTCKAATCATCCATCTATCTTGTGTTATTTCATTGCTTAT
TTACTCATGCATTTTCTGTRTTGGCATATTATTGTGAATGAATGCAGAATCAGAGGATAG
TGTCAATGCTATATACAATCAACTCAACCTTTAGAGGAGCATTTGTCACTCTGCCAGTGT
GTGTTTGTTGAATAATTACTATTTGGAATAATCTCTGTAATACAGTATTTCAATTTCAATG
TTTCATATGTTATTATGTAATATATATGTTGGATTGTTGTCTCAT
```


## References


